/** 技能导航器数据 — 词云与详情页共用 */
window.SKILL_WORDS = [
  { slug: 'flutter', text: 'Flutter', size: 40, eco: 'flutter', title: '🎯 Flutter 跨端开发',
    positioning: '不仅将 Flutter 用于移动端，更致力于 Web / 桌面等跨端场景，追求一套代码、一致体验的高性能交付。',
    depth: ['响应式布局与自适应组件体系', 'CustomPaint / 动画流与复杂交互', 'Riverpod / Bloc 状态管理与模块化路由'],
    projects: [
      { name: 'Faypay Crypto Wallet', summary: '一人独立完成多链加密钱包 App（含应用内全部核心功能），支持 Openverse / ETH / BNB / Polygon。', metric: '一人开发 · App + Web 已上线', url: 'https://faypay.com/' },
      { name: 'PPToken 多链钱包', summary: '助记词体系、多链余额/NFT、Uniswap/Pancake 等 DApp 交互。', metric: '2020–2022 · 钱包全链路' },
      { name: '本作品集站点', summary: '简历站含可交互技术标签墙，Flutter 终极版见 portfolio_app。', metric: 'Flutter Web · 现场演示' },
    ], cta: 'index.html#projects', showPortfolio: true },
  { slug: 'ai-coding', text: 'AI 编程', size: 35, eco: 'ai', title: '🤖 AI 辅助研发',
    positioning: '将大模型与 IDE Agent 深度融入需求分析、编码、测试与重构，用可验收的 Prompt 约束驱动高质量交付。',
    depth: ['Cursor Agent 多文件重构', 'Trae / SOLO Coder 端到端交付', '人机分工：架构与安全由人把关'],
    projects: [], cta: 'index.html#about' },
  { slug: 'solidity', text: 'Solidity', size: 32, eco: 'chain', title: '⛓️ Solidity · 智能合约',
    positioning: '3+ 年智能合约与 DeFi 实战，能从合约设计理解 DApp 交互与安全边界。',
    depth: ['Farm / Pool / NFT 碎片化', 'KYC 与隐私模块协作'],
    projects: [{ name: 'Kaco DeFi · BSC', summary: '智能合约、Farm/Pool、NFT 碎片化与隐私/KYC 模块。', metric: '2022–2025 · BSC 链' }],
    cta: 'index.html#projects' },
  { slug: 'react', text: 'React', size: 28, eco: 'web', title: '⚛️ React 前端工程',
    positioning: '8 年 React 大型项目经验，擅长组件化、链游逻辑层与交易所级复杂业务前端。',
    depth: ['Hooks / 状态分层', 'Ethers.js 链上交互封装'],
    projects: [
      { name: 'Bingo 全链游', summary: 'Web/H5/TG 机器人多端，Ethereum 合约与链上透明交互。', metric: '全平台接入' },
      { name: 'Zytron 平台', summary: 'TVL 分析、页面性能优化，与设计团队协作 UX。', metric: '加载速度显著提升' },
    ], cta: 'index.html#projects' },
  { slug: 'architecture', text: '架构设计', size: 28, eco: 'arch', page: 'architecture.html',
    title: '🏗️ 架构设计 · 现代化工程体系' },
  { slug: 'faypay', text: 'Faypay', size: 36, eco: 'flutter', title: '👛 Faypay · 代表作',
    positioning: '一人独立完成的多链加密钱包 App，可直接在 faypay.com 下载体验。',
    depth: ['Mint / Send / Receive / Request 全链路', '多链资产管理与安全交易'],
    projects: [{ name: 'Faypay Crypto Wallet', summary: '含 App 内全部核心功能，非仅官网展示页。', metric: '商业级多链钱包已上线', url: 'https://faypay.com/' }],
    cta: 'index.html#projects' },
  { slug: 'dart', text: 'Dart', size: 30, eco: 'flutter', title: 'Dart · 跨端语言',
    positioning: 'Flutter 生态核心语言，用于钱包 App 与本站跨端工程化实践。',
    depth: ['空安全与异步模型', '性能敏感模块拆分'],
    projects: [{ name: 'PPToken Wallet', summary: 'Flutter 多链钱包全链路。', metric: '2020–2022' }],
    cta: 'index.html#projects', showPortfolio: true },
  { slug: 'typescript', text: 'TypeScript', size: 26, eco: 'web', title: 'TypeScript',
    positioning: '类型安全驱动的大型 Web3 / 金融前端。',
    depth: ['严格类型边界与 API 契约'],
    projects: [{ name: 'Bingo 全链游', summary: 'TS + Ethers.js 链上交互。', metric: '链游' }],
    cta: 'index.html#projects' },
  { slug: 'trae-cursor', text: 'Trae / Cursor', size: 25, eco: 'ai', title: 'Trae · Cursor 工具链',
    positioning: 'Cursor 精准迭代既有项目；Trae 适合从 0 到 1 的完整页面交付。',
    depth: ['三段式 Prompt：背景 → 约束 → 输出格式'],
    projects: [], cta: 'index.html#about' },
  { slug: 'chrome-extension', text: 'Chrome 插件', size: 24, eco: 'tool', title: '🔌 浏览器钱包插件',
    positioning: '主导多链插件 OpenWallet，覆盖 Solana / EVM / BTC。',
    depth: ['插件沙箱与安全存储', '统一账户模型'],
    projects: [{ name: 'OpenWallet Extension', summary: '多链插件钱包，稳定支持 OpenWallet 生态。', metric: '学神科技 · 主导上线' }],
    cta: 'index.html#projects' },
  { slug: 'nodejs', text: 'Node.js', size: 26, eco: 'tool', title: 'Node.js 全栈支撑',
    positioning: 'Web3 项目自主后端与 BFF，支撑 DApp 快速迭代。',
    depth: ['Express / Koa', '接口聚合与缓存'],
    projects: [{ name: 'ZG 交易所', summary: 'RN + 后端协作的大型交易产品。', metric: '2016–2020' }],
    cta: 'index.html#projects' },
  { slug: 'ethers-js', text: 'Ethers.js', size: 22, eco: 'chain', title: 'Ethers.js · Web3 交互',
    positioning: '链游与钱包场景的标准交互层。',
    depth: ['合约事件订阅与错误恢复'],
    projects: [{ name: 'Bingo 全链游', summary: '链上透明交互。', metric: '多端接入' }],
    cta: 'index.html#projects' },
  { slug: 'performance', text: '性能优化', size: 22, eco: 'soft', title: '⚡ 性能优化',
    positioning: 'Webpack 打包提速、首屏缓存与构建优化，用数据验证体验。',
    depth: ['打包体积 -20% / 构建提速 30%'],
    projects: [{ name: 'Zytron 平台', summary: 'TVL 与页面性能优化。', metric: '显著提升' }],
    cta: 'index.html#projects' },
  { slug: 'ui-ux', text: 'UI / UX', size: 20, eco: 'soft', title: 'UI / UX 协作',
    positioning: '与设计协作落地钱包与 DeFi 产品的可读性与转化路径。',
    depth: ['信息层级与加载态设计'],
    projects: [{ name: 'Faypay', summary: 'C 端钱包动线打磨。', metric: '一人开发', url: 'https://faypay.com/' }],
    cta: 'index.html#projects' },
];

window.ECO_COLORS = {
  flutter: '#38bdf8', ai: '#a78bfa', web: '#22d3ee',
  chain: '#fb923c', arch: '#818cf8', tool: '#4ade80', soft: '#94a3b8',
};

window.getSkillBySlug = function (slug) {
  return window.SKILL_WORDS.find((w) => w.slug === slug);
};
